Add UDPClient and add Timer and Pipeline to StatsdClient
pyflow/basepy pull request #1
Opened 2020-03-02 09:08 UTC by panpan-wu

1. add UDPClient which reconnects automatically when error occurs
2. add Timer and Pipeline to StatsdClient

2020-03-02 09:19 UTC, zeaphoo requested changes

2020-03-02 09:19 UTC, zeaphoo commented on basepy/asynclib/datagram.py
> +class UDPClient:
DatagramAutoClient or DatagramConnection ?

2020-03-02 09:19 UTC, zeaphoo commented on basepy/asynclib/datagram.py
> +                await self._init()
Normal should close the connection when exception on send, re-init the connection when next send called.

2020-03-02 15:39 UTC, zeaphoo requested changes

2020-03-02 15:39 UTC, zeaphoo commented on basepy/asynclib/datagram.py
>      async def init(self):
seems not useful?

2020-03-02 15:39 UTC, zeaphoo commented on basepy/asynclib/datagram.py
> +    async def _init(self):
```suggestion
    async def _get_client(self):
        if self._datagram_client:
            return self._datagram_client
        not_init = self._last_connect_time is None
        waited_longer = int(time.time()) - self._last_connect_time) >= self.RECONNECT_INTERVAL
        if (not_init or waited_longer):
            try:
                await self._connect()
                return self._datagram_client
            except Exception:
                pass
        return None
```

2020-03-02 15:39 UTC, zeaphoo commented on basepy/asynclib/datagram.py
> +    async def _connect(self):
```suggestion
    async def _connect(self):
        self._datagram_client = await connect(self._addr)
        self._last_connect_time = int(time.time())
```

2020-03-02 15:39 UTC, zeaphoo commented on basepy/asynclib/datagram.py
> +        await self._init()
```suggestion
        client = await self._get_client()
        if client is not None:
            try:
                await client.send(data)
            except:
                self.close()
```

2020-03-03 01:41 UTC, panpan-wu commented on basepy/asynclib/datagram.py
>      async def init(self):
init 没有忽略异常，初衷是如果 host 有问题，让外界初始化时能发现，比如 ConnectionRefusedError。而 send 中的初始化是忽略了所有异常，调用 send 不管有没有错误都不会抛出。

2020-03-03 01:44 UTC, zeaphoo commented on basepy/asynclib/datagram.py
>      async def init(self):
有可能会忘记调用这个函数，如果希望做到这个设计，也可以_init(_get_client)里实现。

2020-03-03 01:48 UTC, panpan-wu commented on basepy/asynclib/datagram.py
> +    async def _connect(self):
如果先设置 datagram_client 再设置 last_connect_time，last_connect_time 可能会一直为 None（在 connect 失败时），这样 RECONNECT_INTERVAL 就会失效。相关代码：

not_init = self._last_connect_time is None
waited_longer = int(time.time()) - self._last_connect_time) >= self.RECONNECT_INTERVAL
if (not_init or waited_longer):
    try:
        await self._connect()
        return self._datagram_client
    except Exception:
        pass

2020-03-03 01:53 UTC, zeaphoo commented on basepy/asynclib/datagram.py
> +    async def _connect(self):
这个是我理解错了，_last_connect_time 表示的是去连接的时间，不是连接成功的时间。

2020-03-03 08:20 UTC, zeaphoo approved these changes

2020-03-03 08:20 UTC, merged